# Development environment configuration
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:42606}/sbom?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    druid:
      # 从主配置文件继承大部分 Druid 配置
      url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:42606}/${DB_NAME:SBOM}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:123456}
      
logging:
  level:
    com.oschina.sbom: DEBUG
    org.springframework.web: INFO
    org.mybatis: DEBUG

# 开发环境下显示SQL日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
